common: &common
  :redis_key: "avarus"

production:
  <<: *common
  :redis:
    :host: 'localhost'
    :port: '6379'
    :db: '1'

development:
  <<: *common
  :app_url: 'http://localhost:9292'
  :redis:
    :host: 'localhost'
    :port: '6379'
    :db: '2'

test:
  <<: *common
  :app_url: 'http://localhost'
  :redis:
    :host: 'localhost'
    :port: '6379'
    :db: '3'
